### ISSUE TITLE
addon break if page doesn't have a favicon

### ISSUE THREAD

**Issue by vaff** [sylouuu/chrome-tab-modifier#69]
```javascript
        default_icon = document.querySelectorAll('head link[rel*="icon"]')[0].href;
```

```javascript
Error in response to storage.get: TypeError: Cannot read property 'href' of undefined
    at processPage (chrome-extension://hcbgadmbdkiilgpifjgcakjehmafcjai/js/content.js:16:78)
    at Object.callback (chrome-extension://hcbgadmbdkiilgpifjgcakjehmafcjai/js/content.js:318:5)
    at chrome-extension://hcbgadmbdkiilgpifjgcakjehmafcjai/js/content.js:5:22
```

**Comment by sylouuu** [comment]
Hi,

I just reverted so it will be OK very soon in 0.18.4!

**Comment by vaff** [comment]
roger
